### PR TITLE
😎 Nice Adventure Utils

### PR DESCRIPTION
**Pull request by DasLixou**

### CODE REVIEW

**Comment by CatDevz** [comment]
What is the reason behind renaming asMini to formatMini? That's something that will break projects depending on KStom and for a quite minor reason. 

Either than that it LGTM

**Comment by DasLixou** [comment]
oh sry xD didn't even noticed it. ill change it back. I make these before and then found KStom and pasted it there lol

**Comment by DasLixou** [comment]
that should do it

**Review by CatDevz — APPROVED** [review]
LGTM

**Review by CatDevz — APPROVED** [review]

**Comment by DasLixou** [comment]
will this ever get merged? lol

**Comment by LeoDog896** [comment]
Sorry for the wait -- forgot to watch this repo for push notifications.

**Pull request merged**
